### ISSUE TITLE
[BUG] FileNotFoundException when addBitmapToCache

### ISSUE THREAD

**Issue by bucker** [afreakyelf/Pdf-Viewer#126]
## 📝 Describe the Bug
I found the crash report looks like this:

```
java.io.FileNotFoundException: /data/user/0/com.myapp.www/cache/___pdf___cache___/0: open failed: ENOENT (No such file or directory)
at libcore.io.IoBridge.open(IoBridge.java:574)
at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
at com.rajat.pdfviewer.util.CacheManager$addBitmapToCache$1.invokeSuspend(CacheManager.java:52)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:8)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.java:115)
at com.google.android.play.core.tasks.zzc.run(zzc.java)
at kotlinx.coroutines.scheduling.TaskImpl.run(TaskImpl.java:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.java:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.java:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.java:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:684)
	
Suppressed: P9.i: [v0{Cancelling}@59bb3e6, Dispatchers.IO]
Caused by: android.system.ErrnoException: open failed: ENOENT (No such file or directory)
at libcore.io.Linux.open(Native Method)
at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8781)
at libcore.io.IoBridge.open(IoBridge.java:560)
```

Unable to reproduce it, but seems like it would be possible to access the cache folder `/___pdf___cache___` cache has been `deleteRecursively()`. 

Since the task to [add bitmap to cache](https://github.com/afreakyelf/Pdf-Viewer/blob/master/pdfViewer/src/main/java/com/rajat/pdfviewer/util/CacheManager.kt#L52) will be run on the IO thread, there's no guarantee that the `cacheDir` will exist when it executes.

The solution might be to check the `cacheDir` exists before proceeding, but not sure if I have missed anything.

## 📖 Library Version
- 2.1.1

**Comment by sunilkumarr1995** [comment]
@afreakyelf  any update on this issue because we are also facing the same thing in production ..!! 
any help would be grateful.

**Comment by vivek-np** [comment]
i am facing same issue as well any fixes for this ?

**Comment by real-Darkshadow** [comment]
@afreakyelf any update on this??

**Comment by muazdev26** [comment]
Getting the same issue

**Comment by marin-vasvari** [comment]
To reproduce this you have to leave the app in background for a few minutes while the pdf file is opened. You have also to   enable the Don't keep activity option from the Developer Options before putting the app in background.

**Comment by SkyleKayma** [comment]
This is a big issue in our app too

**Comment by afreakyelf** [comment]
Hey Can you please verify this in https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.2.0
