### ISSUE TITLE
[BUG] Caching causes crash

### ISSUE THREAD

**Issue by MilanJovic92** [afreakyelf/Pdf-Viewer#165]
## 📝 Describe the Bug

The caching mechanism is crashing the application.

## 📖 Library Version
- 2.1.1

## 🚶 Steps to Reproduce

I was unable to reproduce the problem localy.

## 🤔 Expected Behavior

I expect the app not to crash if there is a cache miss.

## 🖼️ Screenshots/Videos

/

## 📱 Smartphone Info:

Crashlytics has reported that it's mostly happening on Samsung devices.

## 💻 Code Snippets

This is how we use the `PdfRenderView`.

```
@Composable
fun PdfRendererComposable(
  file: File,
  statusCallBack: PdfRendererView.StatusCallBack,
  modifier: Modifier = Modifier,
) {
  AndroidView(
    factory = { context ->
      PdfRendererView(context).apply {
        statusListener = statusCallBack

        try {
          initWithFile(file)
        } catch (e: Exception) {
          statusCallBack.onError(e)
        }
      }
    },
    modifier = modifier,
  )
}
```

## 📜 Log Output/Stack Trace

Crash stack trace from the Firebase: 

```
Fatal Exception: java.io.FileNotFoundException: /data/user/0/com.getyourguide.android/cache/___pdf___cache___/1: open failed: ENOENT (No such file or directory)
       at libcore.io.IoBridge.open(IoBridge.java:574)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
       at com.rajat.pdfviewer.util.CacheManager$addBitmapToCache$1.invokeSuspend(CacheManager.kt:52)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
        
```
and
```
Caused by android.system.ErrnoException: open failed: ENOENT (No such file or directory)
       at libcore.io.Linux.open(Linux.java)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
       at libcore.io.BlockGuardOs.open(BlockGuardOs.java:274)
       at libcore.io.ForwardingOs.open(ForwardingOs.java:563)
       at android.app.ActivityThread$AndroidOs.open(ActivityThread.java:8756)
       at libcore.io.IoBridge.open(IoBridge.java:560)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:236)
       at java.io.FileOutputStream.<init>(FileOutputStream.java:186)
       at com.rajat.pdfviewer.util.CacheManager$addBitmapToCache$1.invokeSuspend(CacheManager.kt:52)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
       at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:113)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:89)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:823)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt)
        
```

## 💬 Additional Context
Add any other context about the problem here. Mention if the issue is consistent, specific scenarios where the bug occurs, etc.

---

**Comment by mekutluca** [comment]
Deleting the cached files helped me.

```
    val context = LocalContext.current

    PdfRendererViewCompose(
        url = pdfUrl,
        lifecycleOwner = LocalLifecycleOwner.current,
        statusCallBack = object : PdfRendererView.StatusCallBack {
            override fun onError(error: Throwable) {
                super.onError(error)

                context.cacheDir.listFiles { _, name ->
                    name.contains("pdf")
                }?.forEach { file ->
                    file.delete()
                }
            }

**Comment by afreakyelf** [comment]
Hey Can you please verify this in https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.2.0

**Comment by MilanJovic92** [comment]
Hello.
Sorry, but we stopped using this library, so it will not be easy for me to validate if the error has been fixed.

**Comment by afreakyelf** [comment]
No worries. Thanks!
