### ISSUE TITLE
[BUG] Freezing UI, when trying to load PDF from a file (Jetpack Compose).

### ISSUE THREAD

**Issue by raudonikis** [afreakyelf/Pdf-Viewer#171]
## 📝 Describe the Bug
Freezing UI (for up to ~2 seconds), when trying to load PDF from a file (Jetpack Compose).

## 📖 Library Version
- **PDF Viewer Version:**: 2.1.1

## 🚶 Steps to Reproduce
Please follow these steps to reproduce the issue:
1. **Initial Setup/Library Method Used:** `PdfRendererViewCompose(file = file)`
2. **Actions Taken:** Trying to display the PDF from a file, in a composable.
3. **Unexpected Behavior:** Freezing UI for up to 2 seconds.
4. **Relevant Code/Stack Trace:**
```kotlin
@Composable
fun SomeScreen() {
    PdfRendererViewCompose(
            file = file,
            modifier = Modifier.weight(1f),
            statusCallBack = pdfStatusCallback,
    )
    <...>
}
```

## 🤔 Expected Behavior
UI not freezing :)

## 📱 Smartphone Info:
- **Device:** [e.g., Samsung Galaxy A23, Pixel 8 Pro emulator]
- **OS:** [e.g., Android 14, Android 11]
- **Library Version:** [e.g., 2.1.1]

## 💻 Code Snippets
- Nothing fancy, added code snippets above

## 📜 Log Output/Stack Trace
StrictMode is reporting disk read violations:
```
StrictMode policy violation; ~duration=756 ms: android.os.strictmode.DiskReadViolation
<...>
at android.graphics.pdf.PdfRenderer.<init>(PdfRenderer.java:165)
<...>
at com.rajat.pdfviewer.compose.PdfRendererComposeKt$PdfRendererViewCompose$1.invoke(PdfRendererCompose.kt:33)
<...>
```

**Comment by afreakyelf** [comment]
Hey @raudonikis, Do you mind uploading video of same if you are still facing the issue?

**Comment by raudonikis** [comment]
Here you go, @afreakyelf, this is what the code looks like:

```
Crossfade(isLoading) { isLoading ->
                        if (isLoading.value) {
                            Column(
                                modifier = Modifier.fillMaxSize(),
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.Center
                            ) {
                                CircularProgressIndicator()
                            }
                        } else {
                            AndroidView(
                                factory = { context ->
                                    PdfRendererView(context).apply {
                                        runCatching { initWithFile(file) }
                                    }
                                }
                            )
                        }
                    }
```

https://github.com/user-attachments/assets/c8e3e25a-3fd4-421b-acc2-89169b81fb62

**Comment by afreakyelf** [comment]
Can you try with `PdfRendererViewComposeFromAsset` from new version of library? Maybe this should help!

**Comment by raudonikis** [comment]
`PdfRendererViewComposeFromAsset` doesn't work for my use case, as the pdf is not in assets, but it's a downloaded file. Anyway, I tried the latest library version, and the issue remains.

**Comment by afreakyelf** [comment]
I see @raudonikis , Thank you! I will take a look at it soon!

**Comment by kolyneh** [comment]
Hi there, same issue on PdfRendererView with StrictMode DiskReadViolation, maybe it is just because it read files on main thread.
```
StrictMode policy violation; ~duration=477 ms: android.os.strictmode.DiskReadViolation
...
at android.content.ContentResolver.openFileDescriptor(ContentResolver.java:1635)
at com.rajat.pdfviewer.PdfRendererView.initWithUri(PdfRendererView.kt:123)
...

```

**Comment by afreakyelf** [comment]
Hi, can you verify in https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.3.4. thanks!

**Comment by raudonikis** [comment]
Hi, latest version seems to have fixed the issue, thanks.
