### ISSUE TITLE
Java.lang.RuntimeException: Canvas: trying to draw too large(128545280bytes) bitmap.

### ISSUE THREAD

**Issue by karthikmohan** [afreakyelf/Pdf-Viewer#25]
**Describe the bug**
App crashing because of a major bug. Not able to view PDFs with big pictures.

**To Reproduce**
- Open a pdf with heavy pictures

**Expected behavior**
The app should not crash and view the pdf

**Screenshots**
App is crashing, simple

**Smartphone (please complete the following information):**
 - Device: All
 - Version All

**Additional context**
`2021-09-04 14:49:36.853 810-810/io.esper.files D/AndroidRuntime: Shutting down VM
2021-09-04 14:49:36.876 810-810/io.esper.files E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.esper.files, PID: 810
    java.lang.RuntimeException: Canvas: trying to draw too large(128545280bytes) bitmap.
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:260)
        at android.graphics.Canvas.drawBitmap(Canvas.java:1420)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1286)
        at android.view.View.draw(View.java:18324)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at com.rajat.pdfviewer.PinchZoomRecyclerView.dispatchDraw(PinchZoomRecyclerView.kt:128)
        at android.view.View.draw(View.java:18327)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.updateDisplayListIfDirty(View.java:17297)
        at android.view.View.draw(View.java:18086)
        at android.view.ViewGroup.drawChild(ViewGroup.java:3966)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:3752)
        at android.view.View.draw(View.java:18327)
        at com.android.internal.policy.DecorView.draw(DecorView.java:919)
        at android.view.View.updateDisplayListIfDirty(View.java:17302)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:698)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:806)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3135)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2931)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2523)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1522)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7098)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:638)
2021-09-04 14:49:36.876 810-810/io.esper.files E/AndroidRuntime:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6682)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)`

**Comment by Emefar** [comment]
Same issue

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
