### ISSUE TITLE
App crashes OutOfMemoryError

### ISSUE THREAD

**Issue by Rider02vn** [afreakyelf/Pdf-Viewer#65]
Please check help me.
pdf file about 18MB, and open it via url.

Logs:
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 26952076 byte allocation with 16777216 free bytes and 18MB until OOM
       at dalvik.system.VMRuntime.newNonMovableArray(VMRuntime.java)
       at android.graphics.Bitmap.nativeCreate(Bitmap.java)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:893)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:870)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:837)
       at com.rajat.pdfviewer.PdfRendererCore.buildBitmap(PdfRendererCore.kt:119)
       at com.rajat.pdfviewer.PdfRendererCore.access$buildBitmap(PdfRendererCore.kt:23)
       at com.rajat.pdfviewer.PdfRendererCore$renderPage$1.invokeSuspend(PdfRendererCore.kt:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)

![image](https://i.imgur.com/k2alRQ4.png)

**Comment by afreakyelf** [comment]
Hi, Thank you for using this library. Above issue has been fixed in latest version. 
https://github.com/afreakyelf/Pdf-Viewer/releases/tag/v2.0.1
